### ISSUE TITLE
i3altlayout non si avvia

### ISSUE THREAD

**Issue by nemo231987** [deadc0de6/i3altlayout#3]
good evening, i installed i3altlayout on a mac with gentoo as operating system, i did not receive any error during the installation, i entered the code in the i3 config file but nothing, it is not active, the windows keep opening one next to the 'other...
`nemo@Sparrow ~ $ sudo pip3 install --user i3altlayout
Password: 
Requirement already satisfied: i3altlayout in /root/.local/lib/python3.10/site-packages (1.1.1)
Requirement already satisfied: docopt in /root/.local/lib/python3.10/site-packages (from i3altlayout) (0.6.2)
Requirement already satisfied: i3ipc in /root/.local/lib/python3.10/site-packages (from i3altlayout) (2.2.1)
Requirement already satisfied: python-xlib in /root/.local/lib/python3.10/site-packages (from i3ipc->i3altlayout) (0.31)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3.10/site-packages (from python-xlib->i3ipc->i3altlayout) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
nemo@Sparrow ~ $ mkdir -p /tmp/i3altlayout && pip3 download -d /tmp/i3altlayout i3altlayout
Collecting i3altlayout
  Using cached i3altlayout-1.1.1-py3-none-any.whl (16 kB)
Collecting docopt
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting i3ipc
  Using cached i3ipc-2.2.1-py3-none-any.whl (26 kB)
Collecting python-xlib
  Using cached python_xlib-0.31-py2.py3-none-any.whl (179 kB)
Collecting six>=1.10.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Saved /tmp/i3altlayout/i3altlayout-1.1.1-py3-none-any.whl
Saved /tmp/i3altlayout/docopt-0.6.2.tar.gz
Saved /tmp/i3altlayout/i3ipc-2.2.1-py3-none-any.whl
Saved /tmp/i3altlayout/python_xlib-0.31-py2.py3-none-any.whl
Saved /tmp/i3altlayout/six-1.16.0-py2.py3-none-any.whl
Successfully downloaded i3altlayout docopt i3ipc python-xlib six
nemo@Sparrow ~ $ sudo pip3 install --user --no-index --find-links=/tmp/i3altlayout i3altlayout
Looking in links: /tmp/i3altlayout
Requirement already satisfied: i3altlayout in /root/.local/lib/python3.10/site-packages (1.1.1)
Requirement already satisfied: i3ipc in /root/.local/lib/python3.10/site-packages (from i3altlayout) (2.2.1)
Requirement already satisfied: docopt in /root/.local/lib/python3.10/site-packages (from i3altlayout) (0.6.2)
Requirement already satisfied: python-xlib in /root/.local/lib/python3.10/site-packages (from i3ipc->i3altlayout) (0.31)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3.10/site-packages (from python-xlib->i3ipc->i3altlayout) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
`

**Comment by deadc0de6** [comment]
Hello, 

It sounds like the place where pypi installs binaries is not in your PATH when i3 starts. You have multiple solutions to install with pip3 but using `sudo` and `--user` together is not one of them unless you want to call your pip package from root's home directory.

You can always test if your install is working by simply trying to run `i3altlayout`. If your shell complains it cannot find the binary then probably i3 won't find it neither. If it does find it, then use its absolute path in i3 config to make sure i3 can find it.

* install globally with `sudo pip3 install i3altlayout` and add the absolute path to `i3altlayout` binary to your i3 config (see below)
* install for your user with `pip3 install --user i3altlayout` and add your user pip binary path (usually `/home/<your-user>/.local/bin/`) to your i3 config: `exec --no-startup-id "/home/<your-user>/.local/bin/i3altlayout`
* install i3altlayout and ensure pip3 binary path is in your path before launching i3 (with something like `export PATH="$HOME/.local/bin:$PATH"` for example), then add `exec --no-startup-id "i3altlayout"` in your i3 config

More globally I think you can find where pip3 install its binaries with
* for user package (`--user`): `python3 -m site --user-base`
* for non-user package: `dirname $(which pip3)`

**Comment by nemo231987** [comment]
ok, I followed the second method you described and now it works, thank you

**Comment by deadc0de6** [comment]
awesome :+1:
